
/* Drop Tables */

DROP TABLE IF EXISTS PUBLIC.T_PUBLICACION;
DROP TABLE IF EXISTS PUBLIC.T_SITIO;
DROP TABLE IF EXISTS PUBLIC.T_CATEGORIA;
DROP TABLE IF EXISTS PUBLIC.T_CONTACTO;
DROP TABLE IF EXISTS PUBLIC.T_USUARIO;



/* Drop Sequences */

DROP SEQUENCE IF EXISTS PUBLIC.T_CATEGORIA_CAT_ID_SEQ;
DROP SEQUENCE IF EXISTS PUBLIC.T_PUBLICACION_PUB_ID_SEQ;
DROP SEQUENCE IF EXISTS PUBLIC.T_SITIO_SIT_ID_SEQ;
DROP SEQUENCE IF EXISTS PUBLIC.T_USUARIO_USU_ID_SEQ;




/* Create Tables */

CREATE TABLE PUBLIC.T_CATEGORIA
(
	CAT_ID SERIAL NOT NULL,
	CAT_DESCRIPCION TEXT NOT NULL,
	CONSTRAINT pk_cat PRIMARY KEY (CAT_ID)
) WITHOUT OIDS;


CREATE TABLE PUBLIC.T_CONTACTO
(
	CON_ID_USUARIO INTEGER NOT NULL,
	CON_ID_AMIGO INTEGER NOT NULL,
	CON_FECHA_SOLICITUD DATE NOT NULL,
	CON_FLAG_APROBADO BOOLEAN NOT NULL,
	CONSTRAINT pk_con PRIMARY KEY (CON_ID_USUARIO, CON_ID_AMIGO)
) WITHOUT OIDS;


CREATE TABLE PUBLIC.T_PUBLICACION
(
	PUB_FECHA DATE NOT NULL,
	PUB_COMENTARIO TEXT,
	PUB_FOTO BYTEA,
	PUB_ID_USUARIO INTEGER NOT NULL,
	PUB_ID_SITIO INTEGER NOT NULL,
	PUB_ID SERIAL NOT NULL,
	CONSTRAINT pk_pub PRIMARY KEY (PUB_ID)
) WITHOUT OIDS;


CREATE TABLE PUBLIC.T_SITIO
(
	SIT_NOMBRE TEXT NOT NULL,
	SIT_PUNTO  NOT NULL,
	SIT_PUNTAJE INTEGER,
	SIT_ID_CATEGORIA INTEGER NOT NULL,
	SIT_DIRECCION TEXT NOT NULL,
	SIT_ID SERIAL NOT NULL,
	CONSTRAINT pk_sit PRIMARY KEY (SIT_ID)
) WITHOUT OIDS;


CREATE TABLE PUBLIC.T_USUARIO
(
	USU_NOMBRE TEXT NOT NULL,
	USU_PASSWORD TEXT NOT NULL,
	USU_MAIL TEXT NOT NULL,
	USU_ID SERIAL NOT NULL,
	USU_FECHA_NACIMIENTO DATE,
	USU_FOTO BYTEA,
	CONSTRAINT pk_usu PRIMARY KEY (USU_ID)
) WITHOUT OIDS;



/* Create Foreign Keys */

ALTER TABLE PUBLIC.T_SITIO
	ADD CONSTRAINT FK_SIT_CAT FOREIGN KEY (SIT_ID_CATEGORIA)
	REFERENCES PUBLIC.T_CATEGORIA (CAT_ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE PUBLIC.T_PUBLICACION
	ADD CONSTRAINT FK_PUB_SIT FOREIGN KEY (PUB_ID_SITIO)
	REFERENCES PUBLIC.T_SITIO (SIT_ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE PUBLIC.T_CONTACTO
	ADD CONSTRAINT FK_CON_USU FOREIGN KEY (CON_ID_USUARIO)
	REFERENCES PUBLIC.T_USUARIO (USU_ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE PUBLIC.T_CONTACTO
	ADD CONSTRAINT FK_CON_USU_AMIGO FOREIGN KEY (CON_ID_AMIGO)
	REFERENCES PUBLIC.T_USUARIO (USU_ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE PUBLIC.T_PUBLICACION
	ADD CONSTRAINT FK_SIT_USU FOREIGN KEY (PUB_ID_USUARIO)
	REFERENCES PUBLIC.T_USUARIO (USU_ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;



